apiVersion: v1
kind: Template
metadata:
  labels:
    app: helloservice
  name: helloservice
  namespace: cicd
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: helloservice
    name: helloservice
  spec:
    replicas: 1
    selector:
      app: helloservice
      deploymentconfig: helloservice
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: helloservice
          deploymentconfig: helloservice
      spec:
        containers:
        - image: helloservice
          name: helloservice
          ports:
          - containerPort: 5000
            protocol: TCP
          env:
          - name: HELLOSERVICE_CONFIG
            valueFrom:
              configMapKeyRef:
                name: helloservice-config
                key: 1.properties
    paused: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - helloservice
        from:
          kind: ImageStreamTag
          name: helloservice:latest
          namespace: cicd
      type: ImageChange
