apiVersion: v1
kind: Template
metadata:
  labels:
    app: helloservice
  name: helloservice
  namespace: cicd
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: helloservice
    name: helloservice
    namespace: cicd
  spec:
#    clusterIP: 172.30.117.135
    ports:
    - name: 5000-tcp
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: helloservice
      deploymentconfig: helloservice
    type: ClusterIP
  status:
    loadBalancer: {}